---
title: "Temporary Project Information"
output: html_document
---

!!!Copy starting from the below dashes.

---
title: "Changing"
author: "Elnora Gaiser"
subtitle: --Still working on First Draft, Not quite ready for review.--
---

# Introduction 

  

# Materials and methods 

Install Packages:

```{r, message=F, warning=F}

#Load necessary packages:

library(tidyverse)
library(ggplot2)
library(dplyr)
library(leaflet)
library(sp)
library(sf)

```

Downloading the Data:

* 

```{r, message=F, warning=F}

#Leaflet

noInsp_Clean <- read.csv("data/noInsp_Clean.csv")

class(noInsp_Clean)
colnames(noInsp_Clean) # check to see which columns are longtitude and latitude to map

colnames(noInsp_Clean)
 [1] "X"                        "SUMMONS.NUMBER"          
 [3] "MONTH"                    "DAY"                     
 [5] "YEAR"                     "VIOLATION.TIME"          
 [7] "VIOLATION.DESCRIPTION"    "ORIGINAL.FINE"           
 [9] "VIOLATION.ADDRESS.NUMBER" "VIOLATION.STREET"        
[11] "VIOLATION.FULL.ADDRESS"   "CITY"                    
[13] "STATE"                    "LATITUDE"                
[15] "LONGITUDE"                "LOCATION"                
[17] "COUNCIL.DISTRICT"         "POLICE.DISTRICT"         
[19] "CENSUS.TRACT"             "CENSUS.BLOCK.GROUP"      
[21] "CENSUS.BLOCK"            

noInsp_Coords <- noInsp_Clean[,c(15, 14)] # Change to 15,14



noInsp_Spatial <- SpatialPointsDataFrame(coords = noInsp_Coords, data = noInsp_Clean, proj4string = CRS("+proj=tmerc +lat_0=40 +lon_0=-78.58333333333333 +k=0.9999375 +x_0=350000 +y_0=0 +ellps=GRS80 +units=m +no_defs"))

noInsp_Map <- leaflet(data = noInsp_Clean) %>% addTiles() %>% addMarkers(lng = noInsp_Clean$LONGITUDE, lat = noInsp_Clean$LATITUDE, clusterOptions = markerClusterOptions(showCoverageOnHover = ))

noInsp_Map

```


```{r, message=F, warning=F}

```


# Results

Show tables, plots, etc. and describe them.

```{r}

```

# Conclusions

What have you learned?  Are there any broader implications?

# References

